type Category =
  | "Prénom"
  | "Animal"
  | "Pays"
  | "Ville"
  | "Fruit/Légume"
  | "Objet"
  | "Film"
  | "Métier"
  | "Marque"
  | "Sport"
  | "Couleur"
  | "Vêtement"
  | "Chanteur·se"
  | "Moyen de transport"
  | "Insecte"
  | "Plante"
  | "Boisson"
  | "Émotion"
  | "Célébrité";

type PetitBacDictionary = {
  [letter: string]: {
    [category in Category]?: string[];
  };
};

const Dico: PetitBacDictionary = {
  A: {
    Prénom: ["Alice", "Adam", "Amélie", "Adrien", "Axel"],
    Animal: ["Aigle", "Âne", "Antilope", "Anaconda"],
    Pays: ["Allemagne", "Algérie", "Argentine"],
    Ville: ["Avignon", "Amiens", "Atlanta"],
    "Fruit/Légume": ["Abricot", "Artichaut", "Amande"],
    Objet: ["Agenda", "Arrosoir"],
    Film: ["Avatar", "Amélie", "Avengers"],
    Métier: ["Architecte", "Agriculteur"],
    Marque: ["Adidas", "Apple", "Audi"],
    Sport: ["Athlétisme", "Aïkido"],
    Couleur: ["Argent", "Azur"],
    Vêtement: ["Anorak", "Aube"],
    "Chanteur·se": ["Angèle", "Adele"],
    "Moyen de transport": ["Avion", "Autobus"],
    Insecte: ["Abeille"],
    Plante: ["Acacia", "Aloe vera"],
    Boisson: ["Absinthe", "Agua fresca"],
    Émotion: ["Amour", "Agacement"],
    Célébrité: ["Ariana Grande", "Alain Delon"],
  },
  B: {
    Prénom: ["Béatrice", "Baptiste", "Benjamin"],
    Animal: ["Baleine", "Bouledogue", "Bison"],
    Pays: ["Brésil", "Belgique", "Bulgarie"],
    Ville: ["Bordeaux", "Berlin", "Boston"],
    "Fruit/Légume": ["Banane", "Brocoli", "Betterave"],
    Objet: ["Bouteille", "Brosse"],
    Film: ["Batman", "Braveheart"],
    Métier: ["Boulanger", "Banquier"],
    Marque: ["BMW", "Balenciaga"],
    Sport: ["Basket-ball", "Boxe"],
    Couleur: ["Bleu", "Bordeaux"],
    Vêtement: ["Blouson", "Bermuda"],
    "Chanteur·se": ["Beyoncé", "Bigflo"],
    "Moyen de transport": ["Bateau", "Bus"],
    Insecte: ["Bourdon"],
    Plante: ["Bambou", "Basilic"],
    Boisson: ["Bière", "Bubble tea"],
    Émotion: ["Bonheur", "Boredom"],
    Célébrité: ["Brad Pitt", "Brigitte Bardot"],
  },
  C: {
    Prénom: ["Claire", "Camille", "Charles"],
    Animal: ["Chat", "Chien", "Cobra"],
    Pays: ["Canada", "Chine", "Chili"],
    Ville: ["Caen", "Chicago", "Casablanca"],
    "Fruit/Légume": ["Cerise", "Carotte", "Citron"],
    Objet: ["Crayon", "Couteau"],
    Film: ["Coco", "Cars", "Casablanca"],
    Métier: ["Coiffeur", "Cuisinier"],
    Marque: ["Coca-Cola", "Chanel"],
    Sport: ["Cyclisme", "Canoë"],
    Couleur: ["Cyan", "Crème"],
    Vêtement: ["Chemise", "Casquette"],
    "Chanteur·se": ["Céline Dion", "Clara Luciani"],
    "Moyen de transport": ["Camion", "Caravane"],
    Insecte: ["Chenille"],
    Plante: ["Cactus", "Camomille"],
    Boisson: ["Coca", "Cidre"],
    Émotion: ["Colère", "Calme"],
    Célébrité: ["Cristiano Ronaldo", "Catherine Deneuve"],
  },
  D: {
    Prénom: ["David", "Diane", "Dorothée", "Damien", "Daphné"],
    Animal: ["Dauphin", "Dindon", "Dromadaire", "Dingo"],
    Pays: ["Danemark", "Dominique", "Djibouti"],
    Ville: ["Dijon", "Dubaï", "Detroit"],
    "Fruit/Légume": ["Datte", "Durian", "Dill"],
    Objet: ["Drapeau", "Disque", "Dé"],
    Film: ["Dune", "Die Hard", "Django Unchained"],
    Métier: ["Dentiste", "Danseur", "Développeur"],
    Marque: ["Dior", "Dell", "Dacia"],
    Sport: ["Danse", "Décathlon", "Dressage"],
    Couleur: ["Doré", "Denim"],
    Vêtement: ["Doudoune", "Débardeur"],
    "Chanteur·se": ["Drake", "Dalida", "Dua Lipa"],
    "Moyen de transport": ["Dirigeable", "Diligence"],
    Insecte: ["Demoiselle", "Doryphore"],
    Plante: ["Dahlia", "Digitale"],
    Boisson: ["Diabolo menthe", "Dr Pepper"],
    Émotion: ["Doute", "Dégoût", "Détente"],
    Célébrité: ["Daniel Radcliffe", "Dany Boon"],
  },
  E: {
    Prénom: ["Emma", "Éric", "Élise", "Esteban", "Émilie"],
    Animal: ["Élan", "Émeu", "Escargot", "Écureuil"],
    Pays: ["Espagne", "Estonie", "Égypte"],
    Ville: ["Évreux", "Édimbourg", "Essen"],
    "Fruit/Légume": ["Endive", "Épinard", "Églantine"],
    Objet: ["Éventail", "Équerre", "Écran"],
    Film: ["E.T.", "Erin Brockovich", "Ex Machina"],
    Métier: ["Électricien", "Écrivain", "Éleveur"],
    Marque: ["Epson", "Evian", "Esprit"],
    Sport: ["Escalade", "Escrime", "Équitation"],
    Couleur: ["Émeraude", "Écru"],
    Vêtement: ["Écharpe", "Espadrille"],
    "Chanteur·se": ["Ed Sheeran", "Édith Piaf", "Eminem"],
    "Moyen de transport": ["Élévateur", "Électrobus"],
    Insecte: ["Éphémère"],
    Plante: ["Érable", "Eucalyptus"],
    Boisson: ["Eau", "Earl Grey"],
    Émotion: ["Émerveillement", "Énervement"],
    Célébrité: ["Emma Watson", "Éric Judor"],
  },
  F: {
    Prénom: ["François", "Fanny", "Florian", "Fatima", "Félix"],
    Animal: ["Furet", "Flamant rose", "Fourmi", "Faucon"],
    Pays: ["France", "Finlande", "Fidji"],
    Ville: ["Fréjus", "Florence", "Francfort"],
    "Fruit/Légume": ["Fraise", "Figue", "Fenouil"],
    Objet: ["Fourchette", "Fauteuil", "Fer à repasser"],
    Film: ["Forrest Gump", "Frozen", "Fight Club"],
    Métier: ["Facteur", "Fleuriste", "Forgeron"],
    Marque: ["Ferrari", "Fanta", "Fila"],
    Sport: ["Football", "Formule 1", "Fitness"],
    Couleur: ["Fuchsia", "Fauve"],
    Vêtement: ["Foulard", "Fuseau"],
    "Chanteur·se": ["Francis Cabrel", "Florence Welch", "FKA Twigs"],
    "Moyen de transport": ["Ferry", "Fiacre"],
    Insecte: ["Fourmi", "Frelon"],
    Plante: ["Fougère", "Forsythia"],
    Boisson: ["Fanta", "Frappuccino"],
    Émotion: ["Frustration", "Fierté"],
    Célébrité: ["Frida Kahlo", "Florent Pagny"],
  },
  G: {
    Prénom: ["Gabriel", "Géraldine", "Guillaume", "Gaëlle", "Gaspard"],
    Animal: ["Girafe", "Grenouille", "Guépard", "Gecko", "Grizzly"],
    Pays: ["Grèce", "Guatemala", "Ghana"],
    Ville: ["Grenoble", "Genève", "Guangzhou"],
    "Fruit/Légume": ["Groseille", "Goyave", "Gingembre"],
    Objet: ["Guitare", "Glace", "Gomme", "Grille-pain", "Gobelet"],
    Film: ["Gladiator", "Goodfellas", "Gravity"],
    Métier: ["Garagiste", "Guide touristique", "Géologue"],
    Marque: ["Google", "Gucci", "Gazelle"],
    Sport: ["Golf", "Gymnastique", "Golf"],
    Couleur: ["Gris", "Grenat"],
    Vêtement: ["Gilet", "Gants", "Guêtre"],
    "Chanteur·se": ["Getz, Stan (Jazz)", "Goldman, Jean-Jacques"],
    "Moyen de transport": ["Gondole", "Gyropode"],
    Insecte: ["Guêpe", "Guêpier (oiseau/insectivore)"],
    Plante: ["Géranium", "Genêt"],
    Boisson: ["Gin", "Ginger ale"],
    Émotion: ["Gaieté", "Gratitude"],
    Célébrité: ["Gal Gadot", "Gustavo Lima"],
  },
  H: {
    Prénom: ["Hugo", "Hélène", "Hector", "Hannah", "Honoré"],
    Animal: ["Hippocampe", "Hérisson", "Hibou", "Hamster"],
    Pays: ["Hongrie", "Honduras", "Haïti"],
    Ville: ["Helsinki", "Honolulu", "Hambourg"],
    "Fruit/Légume": ["Haricot", "Honeydew (melon)", "Huckleberry"],
    Objet: ["Horloge", "Hamac", "Haltère", "Huile"],
    Film: ["Harry Potter", "Heat", "Her"],
    Métier: ["Historien", "Hôtesse", "Horloger"],
    Marque: ["Heinz", "Hyundai", "Hugo Boss"],
    Sport: ["Hockey", "Handball", "Halftone?"],
    Couleur: ["Horizontale? (non)", "Havane (beige)"],
    Vêtement: ["Haut", "Haut-de-tennis?"],
    "Chanteur·se": ["Harry Styles", "Helene Fischer"],
    "Moyen de transport": ["Hélicoptère", "Hydroglisseur"],
    Insecte: ["Hirondelle? (oiseau)", "Hanneton"],
    Plante: ["Hortensia", "Houblon"],
    Boisson: ["Houblon (non)", "Hot chocolate"],
    Émotion: ["Humilité", "Hystérie"],
    Célébrité: ["Halle Berry", "Harry Connick Jr."],
  },
  I: {
    Prénom: ["Isabelle", "Ibrahim", "Inès", "Irène", "Ilan"],
    Animal: ["Iguane", "Impala", "Ibis"],
    Pays: ["Islande", "Inde", "Indonésie"],
    Ville: ["Istanbul", "Irkoutsk", "Innsbruck"],
    "Fruit/Légume": ["Igname", "Iceberg (laitue)", "Izmir melon?"],
    Objet: ["Imprimante", "Image", "Instrument"],
    Film: ["Inception", "Indiana Jones", "Interstellar"],
    Métier: ["Ingénieur", "Illustratrice", "Inspecteur"],
    Marque: ["Ikea", "Intel", "Instagram"],
    Sport: ["Ice hockey", "Inline skating", "Iceskating"],
    Couleur: ["Ivoire", "Indigo"],
    Vêtement: ["Imperméable", "Island dress?"],
    "Chanteur·se": ["Alicia Keys (non)", "Iggy Azalea"],
    "Moyen de transport": ["Inboard (yacht)", "Inlands-boat? (non)"],
    Insecte: ["Ixodidae? (tique)"],
    Plante: ["Iris", "Ipomoea"],
    Boisson: ["Ice tea", "Irish coffee"],
    Émotion: ["Irritation", "Inspiration"],
    Célébrité: ["Idris Elba", "Iggy Pop"],
  },
  J: {
    Prénom: ["Julie", "Julien", "Jade", "Jean", "Jérôme"],
    Animal: ["Jaguar", "Jacana", "Jerboa"],
    Pays: ["Japon", "Jordanie", "Jamaïque"],
    Ville: ["Jakarta", "Johannesburg", "Jérusalem"],
    "Fruit/Légume": ["Jujube", "Jacque", "Jambose"],
    Objet: ["Jumelles", "Jeu", "Journal"],
    Film: ["Joker", "Jumanji", "Jurassic Park"],
    Métier: ["Journaliste", "Juge", "Jardinier"],
    Marque: ["Jeep", "Jacadi", "Jordan"],
    Sport: ["Judo", "Jogging", "Jet-ski"],
    Couleur: ["Jaune"],
    Vêtement: ["Jean", "Jupe"],
    "Chanteur·se": ["Johnny Hallyday", "Justin Bieber"],
    "Moyen de transport": ["Jet", "Jeep"],
    Insecte: ["Jasside"],
    Plante: ["Jasmin", "Jonc"],
    Boisson: ["Jus d’orange", "Jägermeister"],
    Émotion: ["Joie", "Jalousie"],
    Célébrité: ["Jack Nicholson", "Jennifer Lopez"],
  },
};
